version: "3.8"

services:
  site:
    build: .  # Constrói a imagem com o Dockerfile
    container_name: meu-site  # Nome fixo para facilitar
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meusite.rule=Host(`gempreendimentos.com`)"
      - "traefik.http.routers.meusite.entrypoints=websecure"
      - "traefik.http.routers.meusite.tls.certresolver=le"
