version: "3.8"

services:
  site:
    image: meu-site:latest  # Usa a imagem local já construída
    container_name: meu-site
    restart: always
    ports:
      - "80:80"  # Expõe a porta do Nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meusite.rule=Host(`gempreendimentos.com`)"
      - "traefik.http.routers.meusite.entrypoints=websecure"
      - "traefik.http.routers.meusite.tls.certresolver=le"